/*
 JavaScript Cookie v2.1.2
 https://github.com/js-cookie/js-cookie

 Copyright 2006, 2015 Klaus Hartl & Fagner Brack
 Released under the MIT license
 @preserve
 jquery.scrolldepth.js | v0.9.1
 Copyright (c) 2016 Rob Flaherty (@robflaherty)
 Licensed under the MIT and GPL licenses.
*/
!function(a){if("function"==typeof define&&define.amd)define(a);else if("object"==typeof exports)module.exports=a();else{var h=window.Cookies,m=window.Cookies=a();m.noConflict=function(){return window.Cookies=h,m}}}(function(){function a(){for(var a=0,f={};a<arguments.length;a++){var g=arguments[a],n;for(n in g)f[n]=g[n]}return f}function h(m){function f(g,n,l){if("undefined"!=typeof document){if(1<arguments.length){if(l=a({path:"/"},f.defaults,l),"number"==typeof l.expires){var k=new Date;k.setMilliseconds(k.getMilliseconds()+
  864E5*l.expires);l.expires=k}try{var h=JSON.stringify(n);/^[\{\[]/.test(h)&&(n=h)}catch(r){}return n=m.write?m.write(n,g):encodeURIComponent(String(n)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent),g=encodeURIComponent(String(g)),g=g.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent),g=g.replace(/[\(\)]/g,escape),document.cookie=[g,"=",n,l.expires&&"; expires="+l.expires.toUTCString(),l.path&&"; path="+l.path,l.domain&&"; domain="+l.domain,l.secure?"; secure":
  ""].join("")}g||(h={});k=document.cookie?document.cookie.split("; "):[];for(var p=/(%[0-9A-Z]{2})+/g,d=0;d<k.length;d++){var v=k[d].split("="),q=v.slice(1).join("=");'"'===q.charAt(0)&&(q=q.slice(1,-1));try{var u=v[0].replace(p,decodeURIComponent);if(q=m.read?m.read(q,u):m(q,u)||q.replace(p,decodeURIComponent),this.json)try{q=JSON.parse(q)}catch(r){}if(g===u){h=q;break}g||(h[u]=q)}catch(r){}}return h}}return f.set=f,f.get=function(a){return f(a)},f.getJSON=function(){return f.apply({json:!0},[].slice.call(arguments))},
  f.defaults={},f.remove=function(g,h){f(g,"",a(h,{expires:-1}))},f.withConverter=h,f}return h(function(){})});
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof module&&module.exports?module.exports=a(require("jquery")):a(jQuery)}(function(a){var h,m,f,g,n={minHeight:0,elements:[],percentage:!0,userTiming:!0,pixelDepth:!0,nonInteraction:!0,gaGlobal:!1,gtmOverride:!1},l=a(window),k=[],w=!1,p=0;a.scrollDepth=function(d){function v(a,c,e,t){g?(g({event:"ScrollDistance",eventCategory:"Scroll Depth",eventAction:a,eventLabel:c,eventValue:1,eventNonInteraction:d.nonInteraction}),
d.pixelDepth&&2<arguments.length&&e>p&&(p=e,g({event:"ScrollDistance",eventCategory:"Scroll Depth",eventAction:"Pixel Depth",eventLabel:(250*Math.floor(e/250)).toString(),eventValue:1,eventNonInteraction:d.nonInteraction})),d.userTiming&&3<arguments.length&&g({event:"ScrollTiming",eventCategory:"Scroll Depth",eventAction:a,eventLabel:c,eventTiming:t})):(h&&(window[f]("send","event","Scroll Depth",a,c,1,{nonInteraction:d.nonInteraction}),d.pixelDepth&&2<arguments.length&&e>p&&(p=e,window[f]("send",
  "event","Scroll Depth","Pixel Depth",(250*Math.floor(e/250)).toString(),1,{nonInteraction:d.nonInteraction})),d.userTiming&&3<arguments.length&&window[f]("send","timing","Scroll Depth",a,t,c)),m&&(_gaq.push(["_trackEvent","Scroll Depth",a,c,1,d.nonInteraction]),d.pixelDepth&&2<arguments.length&&e>p&&(p=e,_gaq.push(["_trackEvent","Scroll Depth","Pixel Depth",(250*Math.floor(e/250)).toString(),1,d.nonInteraction])),d.userTiming&&3<arguments.length&&_gaq.push(["_trackTiming","Scroll Depth",a,t,c,100])))}
  function q(b,c,e){a.each(b,function(b,d){-1===a.inArray(b,k)&&c>=d&&(v("Percentage",b,c,e),k.push(b))})}function u(b,c,e){a.each(b,function(b,d){-1===a.inArray(d,k)&&a(d).length&&c>=a(d).offset().top&&(v("Elements",d,c,e),k.push(d))})}function r(a,c){var b,t,d,f=null,g=0,k=function(){g=new Date;f=null;d=a.apply(b,t)};return function(){var e=new Date;g||(g=e);var h=c-(e-g);return b=this,t=arguments,0>=h?(clearTimeout(f),f=null,g=e,d=a.apply(b,t)):f||(f=setTimeout(k,h)),d}}function x(){w=!0;l.on("scroll.scrollDepth",
    r(function(){var b=a(document).height(),c=window.innerHeight?window.innerHeight:l.height();c=l.scrollTop()+c;b={"25%":parseInt(.25*b,10),"50%":parseInt(.5*b,10),"75%":parseInt(.75*b,10),"100%":b-5};var e=+new Date-y;return k.length>=d.elements.length+(d.percentage?4:0)?(l.off("scroll.scrollDepth"),void(w=!1)):(d.elements&&u(d.elements,c,e),void(d.percentage&&q(b,c,e)))},500))}var y=+new Date;d=a.extend({},n,d);a(document).height()<d.minHeight||(d.gaGlobal?(h=!0,f=d.gaGlobal):"function"==typeof ga?
    (h=!0,f="ga"):"function"==typeof __gaTracker&&(h=!0,f="__gaTracker"),"undefined"!=typeof _gaq&&"function"==typeof _gaq.push&&(m=!0),"function"==typeof d.eventHandler?g=d.eventHandler:"undefined"==typeof dataLayer||"function"!=typeof dataLayer.push||d.gtmOverride||(g=function(a){dataLayer.push(a)}),a.scrollDepth.reset=function(){k=[];p=0;l.off("scroll.scrollDepth");x()},a.scrollDepth.addElements=function(b){"undefined"!=typeof b&&a.isArray(b)&&(a.merge(d.elements,b),w||x())},a.scrollDepth.removeElements=
    function(b){"undefined"!=typeof b&&a.isArray(b)&&a.each(b,function(b,e){var c=a.inArray(e,d.elements),f=a.inArray(e,k);-1!=c&&d.elements.splice(c,1);-1!=f&&k.splice(f,1)})},x())}});
(function(a){function h(a){for(var b={},e=a.split("&"),t=0;t<e.length;t++)a=e[t].split("="),a[0]&&(2>a.length&&a.push(""),b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]));return b}var m={common:{init:function(){w.init();p.init();v.init();q.init();g.init();r.init()},finalize:function(){}},home:{init:function(){},finalize:function(){}},single_product:{init:function(){n.init();d.init()},finalize:function(){}},post_type_archive_press:{init:function(){l.init();k.init()},finalize:function(){}},post_type_archive_help:{init:function(){y.init()},
  finalize:function(){}},search_results:{init:function(){u.init()},finalize:function(){}},page_template_about_us:{init:function(){x.init()},finalize:function(){}},page_template_initiative:{init:function(){y.init()},finalize:function(){}}},f={fire:function(a,c,e){var b;c=void 0===c?"init":c;if(b=(b=""!==a&&m[a])&&"function"===typeof m[a][c])m[a][c](e)},loadEvents:function(){f.fire("common");a.each(document.body.className.replace(/-/g,"_").split(/\s+/),function(a,c){f.fire(c);f.fire(c,"finalize")});f.fire("common",
  "finalize")}},g={el:{button:".js-load-more-articles",container:".js-load-more-container"},loading:0,paged:1,posts_per_page:6,layout:"",init:function(){var b=this,c={};"undefined"==typeof loaded_articles_ids||3!=loaded_articles_ids.length&&4!=loaded_articles_ids.length||(c.posts_per_page=3,b.layout="left");a(document).on("click",b.el.button,function(e){e.preventDefault();if(b.loading||0>b.paged)return!1;b.loading=1;b.layout="left"==b.layout?"right":"left";c.paged=b.paged;c.post__not_in=loaded_articles_ids;
  0<b.layout.length&&(c.layout=b.layout);a.ajax({dataType:"json",url:duracell_theme.api.lang+"/wp-json/duracell/v1/load_articles",data:c,success:function(c){b.loading=0;c.max_num_pages>b.paged?b.paged++:(b.paged=-1,a(b.el.button).closest(".row").hide());a(b.el.container).append(c.html)},error:function(a){}})})}},n={el:{button:".js-load-more-reviews",container:".js-load-more-reviews-container"},loading:0,offset:4,init:function(){var b=this,c={};a(document).on("click",b.el.button,function(e){e.preventDefault();
  if(b.loading||0>b.paged)return!1;b.loading=1;c.offset=b.offset;c.post_id=a(this).data("post_id");a.ajax({dataType:"json",url:duracell_theme.api.lang+"/wp-json/duracell/v1/load_reviews",data:c,success:function(c){b.loading=0;c.max_num>b.offset+4?b.offset+=4:(b.offset=-1,a(b.el.button).closest(".row").hide());a(b.el.container).append(c.html)},error:function(a){}})})}},l={el:{button:".js-load-more-press-assets",container:".js-load-more-press-container"},loading:0,paged:2,init:function(){var b=this,c=
  {};a(document).on("click",b.el.button,function(e){e.preventDefault();if(b.loading||0>b.paged)return!1;b.loading=1;c.paged=b.paged;c.featured_post_id=a(this).data("featured_post_id");a.ajax({dataType:"json",url:duracell_theme.api.lang+"/wp-json/duracell/v1/load_press",data:c,success:function(c){b.loading=0;c.max_num_pages>b.paged?b.paged++:(b.paged=-1,a(b.el.button).closest(".row").hide());a(b.el.container).append(c.html);a(".press-item").matchHeight()},error:function(a){}})})}},k={el:{message:".js-press-auth-error"},
  init:function(){a(this.el.message).get(0)&&a("html,body").animate({scrollTop:a(this.el.message).closest(".press-auth").offset().top-90},"fast")}},w={el:{radio:".js-product-quantity"},init:function(){a(this.el.radio).on("click",function(){var b=a(this).attr("id");if(0<b.indexOf("-popup")){var c=a("#"+b.replace("-popup",""));c.get(0)&&(c.prop("checked",!0),b=c.data("image-ref"),b=a(b),c=c.parent().parent().parent().find(".bin-button"),c.get(0)&&(c=c.attr("id").replace("bin-",""),a("#bin-"+c+"-popup img.packshot").attr("src",
  b.attr("src")),p.generate_popup(c,a(this).data("quantity-code"))))}else a("#"+b+"-popup").prop("checked",!0)});a(this.el.radio).on("change",function(){var b=a(this).data("image-ref");b=a(b);var c=a(this).data("images-ref");c=a(c);c.hide(0,function(){setTimeout(function(){c.not("[data-extra-item]").removeClass("current-packshot");b.addClass("current-packshot").show();a("body.single-product").get(0)&&Duracell.reinitZoomItems()},1)});var e=a(this).parent().parent().parent().find(".bin-button");e.get(0)&&
(e=e.attr("id").replace("bin-",""),a("#bin-"+e+"-popup img.packshot").attr("src",b.attr("src")),p.generate_popup(e,a(this).data("quantity-code")))})}},p={utm_campaign:"",init:function(){void 0!==Cookies.get("relay_utm_campaign")&&(this.utm_campaign=Cookies.get("relay_utm_campaign"));if(0<window.location.search.length){var b=window.location.search.replace("?","");b=h(b);for(var c in b)b.hasOwnProperty(c)&&"utm_campaign"==c&&(Cookies.set("relay_utm_campaign",b[c]),this.utm_campaign=b[c])}a(".js-product-quantity").on("change",
  function(){var b=a(this).parent().parent().parent().find(".bin-button");b.get(0)&&(b.attr("data-quantity-id",a(this).attr("id")),b.attr("data-quantity-code",a(this).data("quantity-code")))});a(document).ready(function(){a(".js-product-quantity:checked").each(function(){var b=a(this).parent().parent().parent().find(".bin-button");b.get(0)&&(b.attr("data-quantity-id",a(this).attr("id")),b.attr("data-quantity-code",a(this).data("quantity-code")));a(this).change()});a(".charger-bin-button").each(function(){var b=
  bin_data[a(this).attr("id").replace("bin-","")][a(this).data("quantity-code")];void 0!==b&&""!==b&&(a(this).removeClass("button-bin-inactive"),a("#bin-"+a(this).attr("id").replace("bin-","")+"-popup img.packshot").attr("src",a(this).parent().parent().parent().find(".charger-image:first").attr("src")))})});a(".bin-button").click(function(b){b.preventDefault();if(!a(this).hasClass("button-bin-inactive")){r.gtm_push(a(this).data("gtm-raw"));a(this).hasClass("charger-bin-button")&&p.generate_popup(a(this).attr("id").replace("bin-",
  ""),a(this).data("quantity-code"));var c=a(this).attr("id");a("#"+c+"-popup").show();a("html,body").addClass("no-scroll");a("#"+c+"-popup").find(".close").on("click",function(b){b.preventDefault();a("#"+c+"-popup").hide();a("html,body").removeClass("no-scroll")})}})},generate_popup:function(b,c){var e=bin_data[b][c];a("#bin-"+b+"-popup .bin-popup-retailers .row").html("");var d="";if(void 0===e||""===e)a("#bin-"+b).addClass("button-bin-inactive"),d=d+'  <div class="col-phone-12 bin-popup-retailer odd">      <div class="row">'+
  ('          <div class="col-phone-12"> <span class="no-data">'+duracell_theme.bin.no_data+"</span> </div>"),d+="      </div>  </div>";else for(a(".bin-"+b).removeClass("button-bin-inactive"),index=0;index<e.length;index++){available="YES"==e[index].available?duracell_theme.bin.in_stock:duracell_theme.bin.out_of_stock;var f=e[index].url;0<p.utm_campaign.length&&(f=-1<f.indexOf("?")?f+("&bannerid="+p.utm_campaign):f+("?bannerid="+p.utm_campaign));d+='  <div class="col-phone-12 bin-popup-retailer odd">';
  d+='      <div class="row">';d+='          <div class="text-center col-phone-4 col-tablet-3 col-desktop-2 col-desktop-push-1"> <img src="'+e[index].logo+'" alt="'+e[index].name+'"> </div>';"YES"==e[index].available?(d+='          <div class="text-center col-phone-4 col-tablet-5 col-desktop-2 col-desktop-push-2"> <span class="in-stock">'+available+"</span> </div>",d+='          <div class="text-center col-phone-4 col-tablet-4 col-desktop-6 col-desktop-push-2"> <a '+e[index].gtm_data_url+' href="'+
    f+'" target="_blank" class="button button-brass">'):(d+='          <div class="text-center col-phone-4 col-tablet-5 col-desktop-2 col-desktop-push-2"> <span class="in-stock in-stock--not">'+available+"</span> </div>",d+='          <div class="text-center col-phone-4 col-tablet-4 col-desktop-6 col-desktop-push-2"> <a href="javascript:void(0)" class="button button-brass button-brass-inverse button-inactive">');d+="      "+duracell_theme.bin.buy_it_not+"</a> </div>";d+="      </div>";d+="  </div>"}a("#bin-"+
  b+"-popup .bin-popup-retailers .row").html(d)}},d={el:{popup_write:".js-popup-review-write",popup_auth:".js-popup-review-auth",popup_duplicate:".js-popup-review-duplicate",button:".js-write-review-button",close:'[class^="js-popup-review-"] .close',popup:".js-popup-review",part_form:".js-review-form",part_message:".js-review-message",part_product:".js-review-product",message_placeholder:".js-review-message h3",review_cancel:".js-review-cancel",review_preview:".js-review-preview",fields:{rating:'[name="rating"]',
  title:'[name="title"]',reviewtext:'[name="reviewtext"]',usernickname:'[name="usernickname"]',userlocation:'[name="userlocation"]',hostedauthentication_authenticationemail:'[name="hostedauthentication_authenticationemail"]',agreedtotermsandconditions:'[name="agreedtotermsandconditions"]'}},processing:0,init:function(){var b=this;a(b.el.button).on("click",function(c){c.preventDefault();b.can_write_review()?b.prepare_form():b.show_message(duracell_theme.review.already_submited,0);b.show_popup(a(b.el.popup_write))});
  a(b.el.close).on("click",function(c){c.preventDefault();b.hide_popup(a(this).closest(".popup-review"))});a(b.el.review_cancel).on("click",function(c){c.preventDefault();b.hide_popup(a(this).closest(".popup-review"))});a(b.el.review_preview).on("click",function(c){c.preventDefault();a(b.el.part_form).submit()});a(b.el.part_form).ajaxForm({beforeSubmit:function(){if(1==b.processing)return!1;a(b.el.review_cancel).addClass("button-inactive");a(b.el.review_preview).addClass("button-inactive");b.processing=
    1;b.hide_form_errors()},success:function(c,e,d,f){b.processing=0;a(b.el.review_cancel).removeClass("button-inactive");a(b.el.review_preview).removeClass("button-inactive");1==c.success?(b.show_message(c.data,1),b.set_review_cookie(),b.clear_form()):"field_errors"==c.type?b.show_form_errors(c.data):"general_error"==c.type&&b.show_form_errors(c.data)},dataType:"json",type:"post",url:"/wp-json/duracell/v1/write_review"})},prepare_form:function(){a(this.el.part_message).hide();a(this.el.part_product).show();
  a(this.el.part_form).show()},prepare_message:function(){a(this.el.part_product).hide();a(this.el.part_form).hide();a(this.el.part_message).show()},show_message:function(b,c){this.prepare_message();a(this.el.popup_write).find(".write-a-review").removeClass("already-submitted thanks");c?a(this.el.popup_write).find(".write-a-review").addClass("thanks"):a(this.el.popup_write).find(".write-a-review").addClass("already-submitted");a(this.el.message_placeholder).html(b)},show_popup:function(b){a("html,body").addClass("no-scroll");
  a(b).fadeIn(250)},hide_popup:function(b){a("html,body").removeClass("no-scroll");a(b).fadeOut(250)},show_form_errors:function(b){a.each(b,function(b,e){var c=a('.js-validation-message[data-ref="'+e.Field.toLowerCase()+'"]');c.find("span").html(e.Message);c.show()})},hide_form_errors:function(){a(".js-validation-message").hide()},clear_form:function(){a(this.el.fields.rating).prop("checked",!1);a(this.el.fields.title).val("");a(this.el.fields.reviewtext).val("");a(this.el.fields.usernickname).val("");
  a(this.el.fields.userlocation).val("");a(this.el.fields.hostedauthentication_authenticationemail).val("");a(this.el.fields.agreedtotermsandconditions).prop("checked",!1)},set_review_cookie:function(){var b=a(this.el.part_form).find('[name="post_id"]').val();Cookies.set("review_"+b,1,{expires:365})},can_write_review:function(){var b=a(this.el.part_form).find('[name="post_id"]').val();return void 0===Cookies.get("review_"+b)}},v={el:{radio:".js-battery-size"},init:function(){a(this.el.radio).on("change",
  function(b){var c=this;if("undefined"!=typeof a(this).data("gtm-raw")){b=function(){window.location.href=a(c).data("ref")};var e=a.extend({},{eventCallback:b},a(this).data("gtm-raw"));r.gtm_push(e);setTimeout(b,1E3)}else window.location=a(this).data("ref")})}},q={el:{select:".js-product-segment"},init:function(){a(this.el.select).on("change.fs",function(){a(this).trigger("change.$")});a(this.el.select).on("change",function(){var b=this;if("undefined"!=typeof a(this).find("option:selected").data("gtm-raw")){var c=
  function(){window.location.href=a(b).val()},e=a.extend({},{eventCallback:c},a(this).find("option:selected").data("gtm-raw"));r.gtm_push(e);setTimeout(c,1E3)}else window.location=a(this).val()})}},u={init:function(){var b=this;a("ul.options li").on("click",function(){b.redirect(a(this).data("raw-value"))});a("select.filter").on("change",function(){b.redirect(a(this).val())})},redirect:function(b){window.location=a("#search-form").attr("action")+"?searchkey="+a('input[name="searchkey"]').val()+"&type="+
  b}},r={el:{home_carousel_pagination:".js-carousel-pagination",primary_menu_for_prof:".js-primary-menu .with-span"},default_event:{event:"duEvent",gaEventCategory:"",gaEventAction:"",gaEventLabel:""},init:function(){var b=this;a("[data-gtm-click]").on("click",function(c){b.gtm_push(a(this).data("gtm-click"))});a(document).on("click","a[data-gtm-url]",function(c){b.url_click(a(this),a(this).data("gtm-url"),c)});a(document).on("gtm_push_event",function(a,e){b.gtm_push(e)});a(document).on("click",b.el.home_carousel_pagination+
  ">span",function(){var c=a(this).index()+1;b.gtm_push(b.prepare_event("hp-carousel","click","Carousel Slide "+c))});a(document).on("click",b.el.primary_menu_for_prof,function(c){var e=b.prepare_event("menu-for-professionals","click",a(this).find("a").attr("href"));b.url_click(a(this).find("a"),e,c)})},url_click:function(b,c,e){var d=function(){window.location.href=b.attr("href")};"undefined"!==typeof b.attr("target")&&"_blank"==b.attr("target")?this.gtm_push(c):(e.preventDefault(),c=a.extend({},{eventCallback:d},
  c),this.gtm_push(c),setTimeout(d,1E3))},prepare_event:function(b,c,e,d){return a.extend({},this.default_event,{gaEventCategory:b,gaEventAction:c,gaEventLabel:e,event:d})},gtm_push:function(a){dataLayer.push(a)}},x={init:function(){a.scrollDepth({percentage:!0,userTiming:!1,pixelDepth:!1,eventHandler:function(a){r.gtm_push(r.prepare_event("about-us-scroll-depth","scroll",a.eventLabel))}})}},y={el:{form:".wpcf7",not_valid_field:".wpcf7-form-control",select_field:".wpcf7-select",file_field:".wpcf7-file"},
  init:function(){var b=this;a(document).on("keyup",b.el.not_valid_field,function(b){a(this).next(".wpcf7-not-valid-tip").get(0)&&a(this).next().fadeOut()});a(document).on("wpcf7:mailsent",b.el.form,function(c){setTimeout(function(){a(this).find(b.el.file_field).next("span").get(0)&&a(this).find(b.el.file_field).next("span").remove();a(this).find(b.el.select_field).trigger("change")}.bind(this),100)})}};a(document).ready(f.loadEvents)})(jQuery);
function social_share(a,h,m,f,g,n,l,k){"undefined"!==typeof n&&"undefined"!==typeof l&&"undefined"!==typeof k&&window.neti_stats.push_event(n,l,k);n=screen.height/2-g/2;l=screen.width/2-f/2;k="";"twitter"==m&&(k="http://twitter.com/share?url="+encodeURIComponent(h)+"&text="+encodeURIComponent(a));"linkedin"==m&&(k="https://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(h)+"&title="+encodeURIComponent(a));"facebook"==m&&(k="https://www.facebook.com/sharer.php?s=100&p[title]="+encodeURIComponent(a)+
  "&p[url]="+encodeURIComponent(h));"weibo"==m&&(k="http://service.weibo.com/share/share.php?url="+encodeURIComponent(h)+"&title="+encodeURIComponent(a));"renren"==m&&(k="http://share.renren.com/share/buttonshare.do?link="+encodeURIComponent(h)+"&title="+encodeURIComponent(a));window.open(k,"sharer","top="+n+",left="+l+",toolbar=0,status=0,width="+f+",height="+g)};
